In [94]:
import os
from pdfminer.high_level import extract_text

In [95]:
rootdir = 'C:/Users/taksa/Desktop/EZ/data/data'
df = pd.DataFrame()
id_ = []
resume_str = []
category = []

for subdir, dirs, files in os.walk(rootdir):
    for file in files:
        path = os.path.join(subdir, file)
        file = open(path, 'rb')
        id_.append(path[-12:-4])
        texts = extract_text(path)
        text = ""
        for i in texts:
            text += i.replace('\n', ' ')
        resume_str.append(text)
        category.append(subdir.split('\\')[1])
        print(path)

C:/Users/taksa/Desktop/EZ/data/data\ACCOUNTANT\13701259.pdf
C:/Users/taksa/Desktop/EZ/data/data\ACCOUNTANT\14055988.pdf
C:/Users/taksa/Desktop/EZ/data/data\ACCOUNTANT\14126433.pdf
C:/Users/taksa/Desktop/EZ/data/data\ACCOUNTANT\14224370.pdf
C:/Users/taksa/Desktop/EZ/data/data\ACCOUNTANT\14449423.pdf

KeyboardInterrupt:

In [92]:
data = {'ID': id_, 'Resume_str': resume_str, 'Category': category}
df = pd.DataFrame(data)  
df

            ID                                         Resume_str    Category
0     13701259  SENIOR ACCOUNTANT Summary Senior Accounting Pr...  ACCOUNTANT
1     14055988  ACCOUNTANT III Summary Talented Accountant Â e...  ACCOUNTANT
2     14126433  SUPERVISOR ACCOUNTANT Professional Summary Abi...  ACCOUNTANT
3     14224370  ACCOUNTANT Summary Degreed accountant with mor...  ACCOUNTANT
4     14449423  STAFF ACCOUNTANT Professional Profile To advan...  ACCOUNTANT
...        ...                                                ...         ...
2465  86322251  READING TEACHER Summary I am a highly motivate...     TEACHER
2466  86597425  HISTORY TEACHER Professional Summary To be emp...     TEACHER
2467  90363254  TEACHER Summary Highly ethical, dependable, an...     TEACHER
2468  96547039  TEACHER Summary  Talented early education prof...     TEACHER
2469  99244405  Kpandipou Koffi Summary  Compassionate teachin...     TEACHER

[2470 rows x 3 columns]

In [100]:
df.to_csv('Resume_Data.csv')

In [99]:
df

,Unnamed: 0,ID,Resume_str,Category
0,0,13701259,SENIOR ACCOUNTANT Summary Senior Accounting Pr...,ACCOUNTANT
1,1,14055988,ACCOUNTANT III Summary Talented Accountant Â e...,ACCOUNTANT
2,2,14126433,SUPERVISOR ACCOUNTANT Professional Summary Abi...,ACCOUNTANT
3,3,14224370,ACCOUNTANT Summary Degreed accountant with mor...,ACCOUNTANT
4,4,14449423,STAFF ACCOUNTANT Professional Profile To advan...,ACCOUNTANT
...,...,...,...,...
2465,2465,86322251,READING TEACHER Summary I am a highly motivate...,TEACHER
2466,2466,86597425,HISTORY TEACHER Professional Summary To be emp...,TEACHER
2467,2467,90363254,"TEACHER Summary Highly ethical, dependable, an...",TEACHER
2468,2468,96547039,TEACHER Summary Talented early education prof...,TEACHER
2469,2469,99244405,Kpandipou Koffi Summary Compassionate teachin...,TEACHER